name: update-chart
on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  weekly-listens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        
      - run: bun install
      - run: bun run build
      - run: bun dist/index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          GIST_ID: ${{ secrets.GIST_ID }}
